platform :ios, '11.0'

use_frameworks!

target 'RxHeartRateMonitors_Example' do
  
  pod 'RxHeartRateMonitors', :path => '../'
  pod 'RxBluetoothKit'
  pod 'RxSwift'
  pod 'RxCocoa'

 post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['RxHeartRateMonitors'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.2'
              end
          end
      end
  end
end
