//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `HeartRateMonitorCell`.
    static let heartRateMonitorCell = _R.nib._HeartRateMonitorCell()
    /// Nib `LaunchScreen`.
    static let launchScreen = _R.nib._LaunchScreen()
    
    /// `UINib(name: "HeartRateMonitorCell", in: bundle)`
    static func heartRateMonitorCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.heartRateMonitorCell)
    }
    
    /// `UINib(name: "LaunchScreen", in: bundle)`
    static func launchScreen(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `HeartRateMonitorCell`.
    static let heartRateMonitorCell: Rswift.ReuseIdentifier<HeartRateMonitorCell> = Rswift.ReuseIdentifier(identifier: "HeartRateMonitorCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 4 storyboards.
  struct storyboard {
    /// Storyboard `AutoConnectVC`.
    static let autoConnectVC = _R.storyboard.autoConnectVC()
    /// Storyboard `HeartRateMonitorVC`.
    static let heartRateMonitorVC = _R.storyboard.heartRateMonitorVC()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `MonitorsVC`.
    static let monitorsVC = _R.storyboard.monitorsVC()
    
    /// `UIStoryboard(name: "AutoConnectVC", bundle: ...)`
    static func autoConnectVC(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.autoConnectVC)
    }
    
    /// `UIStoryboard(name: "HeartRateMonitorVC", bundle: ...)`
    static func heartRateMonitorVC(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.heartRateMonitorVC)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "MonitorsVC", bundle: ...)`
    static func monitorsVC(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.monitorsVC)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    struct _HeartRateMonitorCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = HeartRateMonitorCell
      
      let bundle = R.hostingBundle
      let identifier = "HeartRateMonitorCell"
      let name = "HeartRateMonitorCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> HeartRateMonitorCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? HeartRateMonitorCell
      }
      
      fileprivate init() {}
    }
    
    struct _LaunchScreen: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard {
    struct autoConnectVC: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = AutoConnectVC
      
      let bundle = R.hostingBundle
      let name = "AutoConnectVC"
      
      fileprivate init() {}
    }
    
    struct heartRateMonitorVC: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = HeartRateMonitorVC
      
      let bundle = R.hostingBundle
      let name = "HeartRateMonitorVC"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    struct monitorsVC: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = MonitorsVC
      
      let bundle = R.hostingBundle
      let name = "MonitorsVC"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
